
- name: Create haproxy directory
  file:
    path: /etc/haproxy
    state: directory
- name: Copy HA Proxy files.
  copy: 
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    force: no
  register: haproxy_new
- name: Replace environment variables for haproxy yaml
  replace:
    path: /etc/haproxy/haproxy.cfg
    regexp: '(\${APISERVER_DEST_PORT})'
    replace: "{{ virtual_server_port }}"
  when: "haproxy_new is changed"
- name: Add proxy servers
  block: 
    - name: add manager
      lineinfile:
        insertafter: EOF
        path: /etc/haproxy/haproxy.cfg
        # the whitespace is important to the config file.
        line: "        server {{ item }} {{ hostvars[item]['ansible_default_ipv4'].address }}:{{ kube_port }} check"
      with_items: "{{ groups['k8smanager'] }}"
    - name: add assistants
      lineinfile:
        insertafter: EOF
        path: /etc/haproxy/haproxy.cfg
        # the whitespace is important to the config file.
        line: "        server {{ item }} {{ hostvars[item]['ansible_default_ipv4'].address }}:{{ kube_port }} check"
      with_items: "{{ groups['k8sassistant'] }}"
  when: "haproxy_new is changed"
# If we want to run the services locally we can use this
- name: Install HAProxy
  apt:
    name: "haproxy"
    state: present 
    update_cache: yes
  register: installed_haproxy
- name: Start HAProxy
  systemd:
    daemon_reload: yes
    name: "haproxy"
    state: restarted
    enabled: yes
  when: "installed_haproxy is changed"
