---
- name: install nfs-kernel-server
  apt:
    name: ['nfs-kernel-server', 'nfs-common']
    state: present
    update_cache: true
  register: nfs_installed
  
- name: create default directory
  file:
    path: "{{ nfs_path }}"
    owner: nobody
    group: nogroup
    state: directory  

- name: Share default directory
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_path }} {{ local_network }}(rw,sync,no_root_squash,no_subtree_check)"

- name: reload nfs service
  systemd:
    name: nfs-kernel-server
    state: reloaded
  when: nfs_installed is changed