---
- name: Get Docker Version
  command: docker --version
  register: dockerVersion
- name: Install Buildx (Docker Experimental Builder)
  block:
    - name: build the experimental build kit image
      command: docker build --platform=local -o . git://github.com/docker/buildx
      environment:
        DOCKER_BUILDKIT: 1
    - name: make plugins directory
      file:
        path: '{{ docker_plugins_path }}'
        state: directory
    - name: set plugin
      copy:
        remote_src: true
        dest: '{{ docker_plugins_path }}/docker-buildx'
        src: buildx
        mode: '0755'
  when: '"build" in dockerVersion["stdout"]'
- name: Install OpenFaaS-CLI (Tools)
  block:
    - command: curl -sSL https://cli.openfaas.com -o openfaascli.sh
    - command: sh openfaascli.sh 
- name: Install Make (Tools)
  apt:
    name: make
    state: present
    update_cache: true
- name: Install Node/NPM (JavaScript)
  apt:
    name: ["npm", "nodejs"]
    state: present
    update_cache: true
- name: Install Arkade (Package Manager)
  block:
    - command: curl -SLsf https://dl.get-arkade.dev/ -o arkadecli.sh
    - command: sh arkadecli.sh
- name: Install Helm (Package Manager)
  block:
    - command: snap install helm --classic
    - name: add package repositories
      block:
      - command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - command: helm repo add bitnami https://charts.bitnami.com/bitnami
      - command: helm repo add jetstack https://charts.jetstack.io
    - name: update repositories
      command: helm repo update
