---
- hosts: jenkinsmaster
  order: inventory
  remote_user: root
  tasks:
  - name: Enable docker buildkit
    block:
      - command: "export DOCKER_BUILDKIT=1"
      - command: "docker build --platform=local -o . git://github.com/docker/buildx"
      - file: 
          path: ~/.docker/cli-plugins
          state: directory
      - command: mv buildx ~/.docker/cli-plugins/docker-buildx
