---
- hosts: new
  order: inventory
  remote_user: root
  tasks:
    - name: Install uncomplicated firewall
      apt:
        name: ufw
        update_cache: yes
    - name: Deny everything and enable UFW
      ufw:
        state: enabled
        policy: deny
    - name: Allow everything outgoing
      ufw:
        rule: allow
        direction: out
    - name: Allow SSH
      ufw:
        rule: allow
        port: ssh
