---
- hosts: raspberrypi
  order: inventory
  remote_user: root
  tasks:
    - name: get users on each nodes
      shell: /usr/bin/less /etc/passwd
      register: result
    - name: display the users per node
      debug:
        var: result.stdout_lines