---
- hosts: all
  order: inventory
  tasks:
    - name: Reboot system
      shell: sleep 1s && reboot
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for reboot
      local_action: wait_for host={{ ansible_host }} port=22 state=started delay=10
      become: false