---
- hosts: all
  order: inventory
  tasks:
    - name: test
      debug:
        msg: server {{ item }} {{ hostvars[item]['ansible_default_ipv4'].address }}:{{ virtual_server_source_port }} check"
      with_items: "{{ groups['k8smaster'] }}"
    #   # checks if the current node matches the first node in the k8smastergroup.
      when: "groups['k8smaster'][0] == ansible_facts['nodename']"
    # - name: Add proxy servers
    #   lineinfile:
    #     insertafter: EOF
    #     path: /etc/exports
    #     line: "server {{ item }} {{ hostvars[item]['ansible_default_ipv4'].address }}:{{ virtual_server_source_port }} check"
    #   with_items: "{{ groups['k8smaster'] }}"