---
- name: Update and upgrade packages to their latest version
  apt:
    cache_valid_time: 86400
    update_cache: 'yes'
    autoclean: 'yes'
    autoremove: 'yes'
    upgrade: 'yes'
  register: updated_packages