---
- name: 'set host'
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname

- name: 'update hosts'
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item]['ansible_default_ipv4'].address }}.+$"
    line: "{{ hostvars[item]['ansible_default_ipv4'].address }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}.local"
    state: present
    backup: yes
  with_items: "{{ groups['all'] }}"

- name: 'set timezone'
  timezone:
    name: UTC
  register: timezone

- name: 'check dependencies'
  apt:
    name: ['python', 'python3', 'python-apt', 'apt-transport-https', 'make', nfs-common]
    state: present

- name: Reboot system
  shell: sleep 1s && reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: "(updated_packages is changed) or (swap is changed) or (timezone is changed) or (hostname is changed)"

- name: Wait for reboot
  local_action: wait_for host={{ ansible_host }} port=22 state=started delay=10
  become: false
  when: "(updated_packages is changed) or (swap is changed) or (timezone is changed) or (hostname is changed)"
