---
- name: 'add docker key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: 'add docker repo'
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu eoan stable
    state: present
    filename: kubernetes

- name: 'install docker'
  apt:
    name: ['docker-ce={{ docker_ce_version }}', 'docker-ce-cli={{ docker_ce_version }}', 'docker-compose={{ docker_compose_version }}', 'containerd.io={{ containerd_version }}']
    state: present
    update_cache: yes
  register: docker_installed

- name: 'set daemon configuration'
  copy:
    src: docker.daemon.json
    dest: /etc/docker/daemon.json
  notify: restart Docker

- name: 'lock package versions'
  command: "/usr/bin/apt-mark hold {{ item }}"
  when: docker_installed is changed
  loop:
  - docker-ce
  - docker-ce-cli
  - docker-compose
  - containerd.io

- name: 'flush handlers'
  meta: flush_handlers