---
- name: Create directory
  file:
    path: '/root/docker/ddns'
    state: directory
- name: Run docker-compose file
  block:
    - name: add docker-compose
      template:
        src: docker-compose.yaml.j2
        dest: '/root/docker/ddns/docker-compose.yaml'
        backup: yes
    - name: run docker-compose
      command: 'docker-compose -f "/root/docker/ddns/docker-compose.yaml" up -d --build'