- name: install openfaas-cli
  block:
    - command: curl -sSL https://cli.openfaas.com -o openfaascli.sh
    - command: sh openfaascli.sh 
- name: install OpenFaaS (Functions)
  block:
    - name: get faas cli
      command: arkade get faas-cli
    - name: install openfaas
      command: arkade install openfaas
    - name: service pause
      pause:
        seconds: "{{ service_pause }}"
    - name: expose openfaas
      command: arkade install openfaas-ingress --domain {{ faas_subdomain }}.{{ domain_name }} --email {{ domain_email }}
    - name: get password
      shell: kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode
      register: openfaas_pass
    - name: display pass
      debug:
        var: openfaas_pass.stdout
- name: Install Cron-Connector (Function Triggers)
  command: arkade install cron-connector